Temporary disable build pipeline

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -1,40 +1,40 @@
-name: Build and Push Docker Image
-
-on:
-  push:
-    branches:
-    - master
-
-jobs:
-  build:
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v5
-
-      - name: Build Docker image
-        run: docker build -t dollar-app .
-
-      - name: Run container with test environment vars
-        run: |
-          docker run -d --name test-app -p 8080:8080 \
-            -e SPRING_DATASOURCE_URL="${{ vars.SPRING_DATASOURCE_URL }}" \
-            -e SPRING_DATASOURCE_USERNAME="${{ vars.SPRING_DATASOURCE_USERNAME }}" \
-            -e SPRING_DATASOURCE_PASSWORD="${{ vars.SPRING_DATASOURCE_PASSWORD }}" \
-            dollar-app
-          sleep 15
-          docker logs test-app
-          curl --retry 5 --retry-connrefused http://localhost:8080/health || true
-          docker stop test-app
-
-      - name: Login to Docker Hub
-        uses: docker/login-action@v4
-        with:
-          username: ${{ vars.DOCKER_USERNAME }}
-          password: ${{ vars.DOCKER_PASSWORD }}
-
-      - name: Push to Docker Hub
-        run: |
-          docker tag dollar-app bossbuwi/dollar-app:latest
-          docker push bossbuwi/dollar-app:latest
+#name: Build and Push Docker Image
+#
+#on:
+#  push:
+#    branches:
+#    - master
+#
+#jobs:
+#  build:
+#    runs-on: ubuntu-latest
+#
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v5
+#
+#      - name: Build Docker image
+#        run: docker build -t dollar-app .
+#
+#      - name: Run container with test environment vars
+#        run: |
+#          docker run -d --name test-app -p 8080:8080 \
+#            -e SPRING_DATASOURCE_URL="${{ vars.SPRING_DATASOURCE_URL }}" \
+#            -e SPRING_DATASOURCE_USERNAME="${{ vars.SPRING_DATASOURCE_USERNAME }}" \
+#            -e SPRING_DATASOURCE_PASSWORD="${{ vars.SPRING_DATASOURCE_PASSWORD }}" \
+#            dollar-app
+#          sleep 15
+#          docker logs test-app
+#          curl --retry 5 --retry-connrefused http://localhost:8080/health || true
+#          docker stop test-app
+#
+#      - name: Login to Docker Hub
+#        uses: docker/login-action@v4
+#        with:
+#          username: ${{ vars.DOCKER_USERNAME }}
+#          password: ${{ vars.DOCKER_PASSWORD }}
+#
+#      - name: Push to Docker Hub
+#        run: |
+#          docker tag dollar-app bossbuwi/dollar-app:latest
+#          docker push bossbuwi/dollar-app:latest
